### PR TITLE
Infinifart insanity

### PR DESCRIPTION
**Pull request by joekur**
Can I haz half of your million$?

### CODE REVIEW

**Comment by hungtruong** [comment]
I am worried that this will break my Google Glass.

We should add a voice prompt so the user can choose number of farts, or maybe infinity number?

**Comment by hungtruong** [comment]
Love the idea, though!

**Comment by joekur** [comment]
May I propose a command of "OH GOD MAKE IT STOP" triggering an exit?

**Comment by hungtruong** [comment]
What if the Glass plays a ["brown note"](http://en.wikipedia.org/wiki/Brown_note)? That's more like GoogleAss though I guess.

**Comment by hungtruong** [comment]
@joekur why'd you close this? I was so close to finishing it!

**Comment by joekur** [comment]
Glass is dead 😞  On a brighter note, maybe you could port this to the new atari console?

**Pull request closed without merging**
